# utilizamos una imagen liviana y vacia de linux 
FROM alpine:3.21.3

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY . .

# Comando para ejecutar la aplicación
CMD ["sh"]